### PR TITLE
Disable submit if no tabs present, add int check. Improves #10

### PR DESCRIPTION
**Pull request by ramiabraham**
Disable submit if no tabs present, add int check. Improves #10

### CODE REVIEW

**Comment by sumobi** [comment]
@ramiabraham On master when you try and remove the last custom page it clears out the values. On this Pull you can completely remove the custom page row and the alert isn't shown:

screen shot 2016-05-19 at 1 26 34 pm

**Comment by sumobi** [comment]
Wait, hold that thought, looks like I was cached, or something.

**Comment by sumobi** [comment]
@ramiabraham after your latest commit I'm not seeing the alert anymore, can you doublecheck?

**Comment by sumobi** [comment]
If the "Save Changes" button is disabled (from the earlier screenshot) it doesn't come back to life if you uncheck the default tabs:

screen shot 2016-05-19 at 1 34 49 pm

**Comment by ramiabraham** [comment]
Yeah the state has to be updated each time a checkbox is checked/unchecked to get the proper .length of all the checkboxes, and set the boolean accordingly.

I have something in mind (a guard-clause stack, borrowing it from parsley.js) - will start with this tomorrow :)

**Comment by michaelbeil** [comment]
There is still an issue upon save when no tabs are selected. The modal shows after the page is saved.

**Comment by ramiabraham** [comment]
_Closing in favor of pulling against https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/tree/release/1.1.2_

**Pull request closed without merging**
